name: Generate PDF with Pandoc
on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc texlive-xetex
      - name: Convert to PDF
        run: pandoc README.md -o README.pdf --pdf-engine=xelatex
      - uses: actions/upload-artifact@v4
        with:
          name: README.pdf
          path: README.pdf
